trigger.action.setUserFlag("SSB",100)

--Blue OBJ Flounder
trigger.action.setUserFlag("Bravo Apache-1",0)
trigger.action.setUserFlag("Bravo Apache-2",0)
trigger.action.setUserFlag("Bravo Apache-3",0)
trigger.action.setUserFlag("Bravo Apache-4",0)
trigger.action.setUserFlag("Bravo Shark-1",0)
trigger.action.setUserFlag("Bravo Shark-2",0)
trigger.action.setUserFlag("Bravo Shark-3",0)
trigger.action.setUserFlag("Bravo Shark-4",0)
trigger.action.setUserFlag("Bravo Hind-1",0)
trigger.action.setUserFlag("Bravo Hind-2",0)
trigger.action.setUserFlag("Bravo Hind-3",0)
trigger.action.setUserFlag("Bravo Hind-4",0)
trigger.action.setUserFlag("Bravo Hip-1",0)
trigger.action.setUserFlag("Bravo Hip-2",0)
trigger.action.setUserFlag("Bravo Hip-3",0)
trigger.action.setUserFlag("Bravo Hip-4",0)
trigger.action.setUserFlag("Bravo Huey-1",0)
trigger.action.setUserFlag("Bravo Huey-2",0)
trigger.action.setUserFlag("Bravo Huey-3",0)
trigger.action.setUserFlag("Bravo Huey-4",0)
trigger.action.setUserFlag("Bravo Gazelle-1",0)
trigger.action.setUserFlag("Bravo Gazelle-2",0)
trigger.action.setUserFlag("Bravo Gazelle-3",0)
trigger.action.setUserFlag("Bravo Gazelle-4",0)



--Red OBJ Flounder
trigger.action.setUserFlag("Bravo Apache-1",100)
trigger.action.setUserFlag("Bravo Apache-2",100)
trigger.action.setUserFlag("Bravo Apache-3",100)
trigger.action.setUserFlag("Bravo Apache-4",100)
trigger.action.setUserFlag("Bravo Shark-1",100)
trigger.action.setUserFlag("Bravo Shark-2",100)
trigger.action.setUserFlag("Bravo Shark-3",100)
trigger.action.setUserFlag("Bravo Shark-4",100)
trigger.action.setUserFlag("Bravo Hind-1",100)
trigger.action.setUserFlag("Bravo Hind-2",100)
trigger.action.setUserFlag("Bravo Hind-3",100)
trigger.action.setUserFlag("Bravo Hind-4",100)
trigger.action.setUserFlag("Bravo Hip-1",100)
trigger.action.setUserFlag("Bravo Hip-2",100)
trigger.action.setUserFlag("Bravo Hip-3",100)
trigger.action.setUserFlag("Bravo Hip-4",100)
trigger.action.setUserFlag("Bravo Huey-1",100)
trigger.action.setUserFlag("Bravo Huey-2",100)
trigger.action.setUserFlag("Bravo Huey-3",100)
trigger.action.setUserFlag("Bravo Huey-4",100)
trigger.action.setUserFlag("Bravo Gazelle-1",100)
trigger.action.setUserFlag("Bravo Gazelle-2",100)
trigger.action.setUserFlag("Bravo Gazelle-3",100)
trigger.action.setUserFlag("Bravo Gazelle-4",100)

--blue Obj Sabre
trigger.action.setUserFlag("Charlie Apache-1",0)
trigger.action.setUserFlag("Charlie Apache-2",0)
trigger.action.setUserFlag("Charlie Apache-3",0)
trigger.action.setUserFlag("Charlie Apache-4",0)
trigger.action.setUserFlag("Charlie Shark-1",0)
trigger.action.setUserFlag("Charlie Shark-2",0)
trigger.action.setUserFlag("Charlie Shark-3",0)
trigger.action.setUserFlag("Charlie Shark-4",0)
trigger.action.setUserFlag("Charlie Hind-1",0)
trigger.action.setUserFlag("Charlie Hind-2",0)
trigger.action.setUserFlag("Charlie Hind-3",0)
trigger.action.setUserFlag("Charlie Hind-4",0)
trigger.action.setUserFlag("Charlie Hip-1",0)
trigger.action.setUserFlag("Charlie Hip-2",0)
trigger.action.setUserFlag("Charlie Hip-3",0)
trigger.action.setUserFlag("Charlie Hip-4",0)
trigger.action.setUserFlag("Charlie Huey-1",0)
trigger.action.setUserFlag("Charlie Huey-2",0)
trigger.action.setUserFlag("Charlie Huey-3",0)
trigger.action.setUserFlag("Charlie Huey-4",0)
trigger.action.setUserFlag("Charlie Gazelle-1",0)
trigger.action.setUserFlag("Charlie Gazelle-2",0)
trigger.action.setUserFlag("Charlie Gazelle-3",0)
trigger.action.setUserFlag("Charlie Gazelle-4",0)


--red Obj Sabre
trigger.action.setUserFlag("Charlie Apache-1",100)
trigger.action.setUserFlag("Charlie Apache-2",100)
trigger.action.setUserFlag("Charlie Apache-3",100)
trigger.action.setUserFlag("Charlie Apache-4",100)
trigger.action.setUserFlag("Charlie Shark-1",100)
trigger.action.setUserFlag("Charlie Shark-2",100)
trigger.action.setUserFlag("Charlie Shark-3",100)
trigger.action.setUserFlag("Charlie Shark-4",100)
trigger.action.setUserFlag("Charlie Hind-1",100)
trigger.action.setUserFlag("Charlie Hind-2",100)
trigger.action.setUserFlag("Charlie Hind-3",100)
trigger.action.setUserFlag("Charlie Hind-4",100)
trigger.action.setUserFlag("Charlie Hip-1",100)
trigger.action.setUserFlag("Charlie Hip-2",100)
trigger.action.setUserFlag("Charlie Hip-3",100)
trigger.action.setUserFlag("Charlie Hip-4",100)
trigger.action.setUserFlag("Charlie Huey-1",100)
trigger.action.setUserFlag("Charlie Huey-2",100)
trigger.action.setUserFlag("Charlie Huey-3",100)
trigger.action.setUserFlag("Charlie Huey-4",100)
trigger.action.setUserFlag("Charlie Gazelle-1",100)
trigger.action.setUserFlag("Charlie Gazelle-2",100)
trigger.action.setUserFlag("Charlie Gazelle-3",100)
trigger.action.setUserFlag("Charlie Gazelle-4",100)

--blue Gudauta
trigger.action.setUserFlag("Gudauta Blue Viper-1",0)


--red Gudauta
trigger.action.setUserFlag("Gudauta Blue Viper-1",100)


--Blue Beslan
trigger.action.setUserFlag("Beslan Blue Viper-1",0)
trigger.action.setUserFlag("Beslan Blue Viper-2",0)
trigger.action.setUserFlag("Beslan Blue Viper-3",0)
trigger.action.setUserFlag("Beslan Blue Mirage-1",0)
trigger.action.setUserFlag("Beslan Blue Mirage-2",0)
trigger.action.setUserFlag("Beslan Blue Mirage-3",0)
trigger.action.setUserFlag("Beslan Blue WarthogC2-1",0)
trigger.action.setUserFlag("Beslan Blue WarthogC2-2",0)
trigger.action.setUserFlag("Beslan Blue WarthogC2-3",0)
trigger.action.setUserFlag("Beslan Blue WarthogA-1",0)
trigger.action.setUserFlag("Beslan Blue WarthogA-2",0)
trigger.action.setUserFlag("Beslan Blue Viggen-1",0)
trigger.action.setUserFlag("Beslan Blue Viggen-2",0)
trigger.action.setUserFlag("Beslan Blue Harrier-1",0)
trigger.action.setUserFlag("Beslan Blue Harrier-2",0)
trigger.action.setUserFlag("Beslan Blue Hornet-1",0)
trigger.action.setUserFlag("Beslan Blue Hornet-2",0)
trigger.action.setUserFlag("Beslan Blue Hornet-3",0)
trigger.action.setUserFlag("Beslan Blue TomcatB-1",0)
trigger.action.setUserFlag("Beslan Blue TomcatB-2",0)
trigger.action.setUserFlag("Beslan Blue TomcatB-3",0)
trigger.action.setUserFlag("Beslan Blue Tiger-1",0)
trigger.action.setUserFlag("Beslan Blue Tiger-2",0)
trigger.action.setUserFlag("Beslan Blue Tiger-3",0)
trigger.action.setUserFlag("Beslan Blue Eagle-1",0)
trigger.action.setUserFlag("Beslan Blue Eagle-2",0)
trigger.action.setUserFlag("Beslan Blue Eagle-3",0)
trigger.action.setUserFlag("Beslan Red SU25-1",100)
trigger.action.setUserFlag("Beslan Red SU25-2",100)
trigger.action.setUserFlag("Beslan Red SU25-3",100)
trigger.action.setUserFlag("Beslan Red SU25T-1",100)
trigger.action.setUserFlag("Beslan Red SU25T-2",100)
trigger.action.setUserFlag("Beslan Red SU25T-3",100)
trigger.action.setUserFlag("Beslan Red Thunder-1",100)
trigger.action.setUserFlag("Beslan Red Thunder-2",100)
trigger.action.setUserFlag("Beslan Red Thunder-3",100)
trigger.action.setUserFlag("Beslan Red Fishbed-1",100)
trigger.action.setUserFlag("Beslan Red Fishbed-2",100)
trigger.action.setUserFlag("Beslan Red Fishbed-3",100)
trigger.action.setUserFlag("Beslan Red FulcrumA-1",100)
trigger.action.setUserFlag("Beslan Red FulcrumA-2",100)
trigger.action.setUserFlag("Beslan Red FulcrumA-3",100)
trigger.action.setUserFlag("Beslan Red FulcrumS-1",100)
trigger.action.setUserFlag("Beslan Red FulcrumS-2",100)
trigger.action.setUserFlag("Beslan Red FulcrumS-3",100)
trigger.action.setUserFlag("Beslan Red FlankerD-1",100)
trigger.action.setUserFlag("Beslan Red FlankerD-2",100)
trigger.action.setUserFlag("Beslan Red FlankerD-3",100)
trigger.action.setUserFlag("Beslan Red FlankerL-1",100)
trigger.action.setUserFlag("Beslan Red FlankerL-2",100)
trigger.action.setUserFlag("Beslan Red FlankerL-3",100)
trigger.action.setUserFlag("Beslan Red Farmer-1",100)
trigger.action.setUserFlag("Beslan Red Farmer-2",100)
trigger.action.setUserFlag("Beslan Red Farmer-3",100)
trigger.action.setUserFlag("Beslan Red F16-1",100)
trigger.action.setUserFlag("Beslan Red F16-2",100)
trigger.action.setUserFlag("Beslan Red F16-3",100)
trigger.action.setUserFlag("Beslan Red F14A-1",100)
trigger.action.setUserFlag("Beslan Red F14A-2",100)
trigger.action.setUserFlag("Beslan Red F14A-3",100)
trigger.action.setUserFlag("Beslan Red F5E-1",100)
trigger.action.setUserFlag("Beslan Red F5E-2",100)
trigger.action.setUserFlag("Beslan Red F5E-3",100)

--red Beslan
trigger.action.setUserFlag("Beslan Blue Viper-1",100)
trigger.action.setUserFlag("Beslan Blue Viper-2",100)
trigger.action.setUserFlag("Beslan Blue Viper-3",100)
trigger.action.setUserFlag("Beslan Blue Mirage-1",100)
trigger.action.setUserFlag("Beslan Blue Mirage-2",100)
trigger.action.setUserFlag("Beslan Blue Mirage-3",100)
trigger.action.setUserFlag("Beslan Blue WarthogC2-1",100)
trigger.action.setUserFlag("Beslan Blue WarthogC2-2",100)
trigger.action.setUserFlag("Beslan Blue WarthogC2-3",100)
trigger.action.setUserFlag("Beslan Blue WarthogA-1",100)
trigger.action.setUserFlag("Beslan Blue WarthogA-2",100)
trigger.action.setUserFlag("Beslan Blue Viggen-1",100)
trigger.action.setUserFlag("Beslan Blue Viggen-2",100)
trigger.action.setUserFlag("Beslan Blue Harrier-1",100)
trigger.action.setUserFlag("Beslan Blue Harrier-2",100)
trigger.action.setUserFlag("Beslan Blue Hornet-1",100)
trigger.action.setUserFlag("Beslan Blue Hornet-2",100)
trigger.action.setUserFlag("Beslan Blue Hornet-3",100)
trigger.action.setUserFlag("Beslan Blue TomcatB-1",100)
trigger.action.setUserFlag("Beslan Blue TomcatB-2",100)
trigger.action.setUserFlag("Beslan Blue TomcatB-3",100)
trigger.action.setUserFlag("Beslan Blue Tiger-1",100)
trigger.action.setUserFlag("Beslan Blue Tiger-2",100)
trigger.action.setUserFlag("Beslan Blue Tiger-3",100)
trigger.action.setUserFlag("Beslan Blue Eagle-1",100)
trigger.action.setUserFlag("Beslan Blue Eagle-2",100)
trigger.action.setUserFlag("Beslan Blue Eagle-3",100)
trigger.action.setUserFlag("Beslan Red SU25-1",0)
trigger.action.setUserFlag("Beslan Red SU25-2",0)
trigger.action.setUserFlag("Beslan Red SU25-3",0)
trigger.action.setUserFlag("Beslan Red SU25T-1",0)
trigger.action.setUserFlag("Beslan Red SU25T-2",0)
trigger.action.setUserFlag("Beslan Red SU25T-3",0)
trigger.action.setUserFlag("Beslan Red Thunder-1",0)
trigger.action.setUserFlag("Beslan Red Thunder-2",0)
trigger.action.setUserFlag("Beslan Red Thunder-3",0)
trigger.action.setUserFlag("Beslan Red Fishbed-1",0)
trigger.action.setUserFlag("Beslan Red Fishbed-2",0)
trigger.action.setUserFlag("Beslan Red Fishbed-3",0)
trigger.action.setUserFlag("Beslan Red FulcrumA-1",0)
trigger.action.setUserFlag("Beslan Red FulcrumA-2",0)
trigger.action.setUserFlag("Beslan Red FulcrumA-3",0)
trigger.action.setUserFlag("Beslan Red FulcrumS-1",0)
trigger.action.setUserFlag("Beslan Red FulcrumS-2",0)
trigger.action.setUserFlag("Beslan Red FulcrumS-3",0)
trigger.action.setUserFlag("Beslan Red FlankerD-1",0)
trigger.action.setUserFlag("Beslan Red FlankerD-2",0)
trigger.action.setUserFlag("Beslan Red FlankerD-3",0)
trigger.action.setUserFlag("Beslan Red FlankerL-1",0)
trigger.action.setUserFlag("Beslan Red FlankerL-2",0)
trigger.action.setUserFlag("Beslan Red FlankerL-3",0)
trigger.action.setUserFlag("Beslan Red Farmer-1",0)
trigger.action.setUserFlag("Beslan Red Farmer-2",0)
trigger.action.setUserFlag("Beslan Red Farmer-3",0)
trigger.action.setUserFlag("Beslan Red F16-1",0)
trigger.action.setUserFlag("Beslan Red F16-2",0)
trigger.action.setUserFlag("Beslan Red F16-3",0)
trigger.action.setUserFlag("Beslan Red F14A-1",0)
trigger.action.setUserFlag("Beslan Red F14A-2",0)
trigger.action.setUserFlag("Beslan Red F14A-3",0)
trigger.action.setUserFlag("Beslan Red F5E-1",0)
trigger.action.setUserFlag("Beslan Red F5E-2",0)
trigger.action.setUserFlag("Beslan Red F5E-3",0)

--blue Vody
trigger.action.setUserFlag("Vody Blue Viper-1",0)
trigger.action.setUserFlag("Vody Blue Viper-2",0)
trigger.action.setUserFlag("Vody Blue Viper-3",0)
trigger.action.setUserFlag("Vody Blue Mirage-1",0)
trigger.action.setUserFlag("Vody Blue Mirage-2",0)
trigger.action.setUserFlag("Vody Blue Mirage-3",0)
trigger.action.setUserFlag("Vody Blue WarthogC2-1",0)
trigger.action.setUserFlag("Vody Blue WarthogC2-2",0)
trigger.action.setUserFlag("Vody Blue WarthogC2-3",0)
trigger.action.setUserFlag("Vody Blue WarthogA-1",0)
trigger.action.setUserFlag("Vody Blue WarthogA-2",0)
trigger.action.setUserFlag("Vody Blue Viggen-1",0)
trigger.action.setUserFlag("Vody Blue Viggen-2",0)
trigger.action.setUserFlag("Vody Blue Harrier-1",0)
trigger.action.setUserFlag("Vody Blue Harrier-2",0)
trigger.action.setUserFlag("Vody Blue Hornet-1",0)
trigger.action.setUserFlag("Vody Blue Hornet-2",0)
trigger.action.setUserFlag("Vody Blue Hornet-3",0)
trigger.action.setUserFlag("Vody Blue TomcatB-1",0)
trigger.action.setUserFlag("Vody Blue TomcatB-2",0)
trigger.action.setUserFlag("Vody Blue TomcatB-3",0)
trigger.action.setUserFlag("Vody Blue Tiger-1",0)
trigger.action.setUserFlag("Vody Blue Tiger-2",0)
trigger.action.setUserFlag("Vody Blue Tiger-3",0)
trigger.action.setUserFlag("Vody Blue Eagle-1",0)
trigger.action.setUserFlag("Vody Blue Eagle-2",0)
trigger.action.setUserFlag("Vody Blue Eagle-3",0)
trigger.action.setUserFlag("Vody Red SU25-1",100)
trigger.action.setUserFlag("Vody Red SU25-2",100)
trigger.action.setUserFlag("Vody Red SU25-3",100)
trigger.action.setUserFlag("Vody Red SU25T-1",100)
trigger.action.setUserFlag("Vody Red SU25T-2",100)
trigger.action.setUserFlag("Vody Red SU25T-3",100)
trigger.action.setUserFlag("Vody Red Thunder-1",100)
trigger.action.setUserFlag("Vody Red Thunder-2",100)
trigger.action.setUserFlag("Vody Red Thunder-3",100)
trigger.action.setUserFlag("Vody Red Fishbed-1",100)
trigger.action.setUserFlag("Vody Red Fishbed-2",100)
trigger.action.setUserFlag("Vody Red Fishbed-3",100)
trigger.action.setUserFlag("Vody Red FulcrumA-1",100)
trigger.action.setUserFlag("Vody Red FulcrumA-2",100)
trigger.action.setUserFlag("Vody Red FulcrumA-3",100)
trigger.action.setUserFlag("Vody Red FulcrumS-1",100)
trigger.action.setUserFlag("Vody Red FulcrumS-2",100)
trigger.action.setUserFlag("Vody Red FulcrumS-3",100)
trigger.action.setUserFlag("Vody Red FlankerD-1",100)
trigger.action.setUserFlag("Vody Red FlankerD-2",100)
trigger.action.setUserFlag("Vody Red FlankerD-3",100)
trigger.action.setUserFlag("Vody Red FlankerL-1",100)
trigger.action.setUserFlag("Vody Red FlankerL-2",100)
trigger.action.setUserFlag("Vody Red FlankerL-3",100)
trigger.action.setUserFlag("Vody Red Farmer-1",100)
trigger.action.setUserFlag("Vody Red Farmer-2",100)
trigger.action.setUserFlag("Vody Red Farmer-3",100)
trigger.action.setUserFlag("Vody Red F16-1",100)
trigger.action.setUserFlag("Vody Red F16-2",100)
trigger.action.setUserFlag("Vody Red F16-3",100)
trigger.action.setUserFlag("Vody Red F14A-1",100)
trigger.action.setUserFlag("Vody Red F14A-2",100)
trigger.action.setUserFlag("Vody Red F14A-3",100)
trigger.action.setUserFlag("Vody Red F5E-1",100)
trigger.action.setUserFlag("Vody Red F5E-2",100)
trigger.action.setUserFlag("Vody Red F5E-3",100)

--red Vody
trigger.action.setUserFlag("Vody Blue Viper-1",100)
trigger.action.setUserFlag("Vody Blue Viper-2",100)
trigger.action.setUserFlag("Vody Blue Viper-3",100)
trigger.action.setUserFlag("Vody Blue Mirage-1",100)
trigger.action.setUserFlag("Vody Blue Mirage-2",100)
trigger.action.setUserFlag("Vody Blue Mirage-3",100)
trigger.action.setUserFlag("Vody Blue WarthogC2-1",100)
trigger.action.setUserFlag("Vody Blue WarthogC2-2",100)
trigger.action.setUserFlag("Vody Blue WarthogC2-3",100)
trigger.action.setUserFlag("Vody Blue WarthogA-1",100)
trigger.action.setUserFlag("Vody Blue WarthogA-2",100)
trigger.action.setUserFlag("Vody Blue Viggen-1",100)
trigger.action.setUserFlag("Vody Blue Viggen-2",100)
trigger.action.setUserFlag("Vody Blue Harrier-1",100)
trigger.action.setUserFlag("Vody Blue Harrier-2",100)
trigger.action.setUserFlag("Vody Blue Hornet-1",100)
trigger.action.setUserFlag("Vody Blue Hornet-2",100)
trigger.action.setUserFlag("Vody Blue Hornet-3",100)
trigger.action.setUserFlag("Vody Blue TomcatB-1",100)
trigger.action.setUserFlag("Vody Blue TomcatB-2",100)
trigger.action.setUserFlag("Vody Blue TomcatB-3",100)
trigger.action.setUserFlag("Vody Blue Tiger-1",100)
trigger.action.setUserFlag("Vody Blue Tiger-2",100)
trigger.action.setUserFlag("Vody Blue Tiger-3",100)
trigger.action.setUserFlag("Vody Blue Eagle-1",100)
trigger.action.setUserFlag("Vody Blue Eagle-2",100)
trigger.action.setUserFlag("Vody Blue Eagle-3",100)
trigger.action.setUserFlag("Vody Red SU25-1",0)
trigger.action.setUserFlag("Vody Red SU25-2",0)
trigger.action.setUserFlag("Vody Red SU25-3",0)
trigger.action.setUserFlag("Vody Red SU25T-1",0)
trigger.action.setUserFlag("Vody Red SU25T-2",0)
trigger.action.setUserFlag("Vody Red SU25T-3",0)
trigger.action.setUserFlag("Vody Red Thunder-1",0)
trigger.action.setUserFlag("Vody Red Thunder-2",0)
trigger.action.setUserFlag("Vody Red Thunder-3",0)
trigger.action.setUserFlag("Vody Red Fishbed-1",0)
trigger.action.setUserFlag("Vody Red Fishbed-2",0)
trigger.action.setUserFlag("Vody Red Fishbed-3",0)
trigger.action.setUserFlag("Vody Red FulcrumA-1",0)
trigger.action.setUserFlag("Vody Red FulcrumA-2",0)
trigger.action.setUserFlag("Vody Red FulcrumA-3",0)
trigger.action.setUserFlag("Vody Red FulcrumS-1",0)
trigger.action.setUserFlag("Vody Red FulcrumS-2",0)
trigger.action.setUserFlag("Vody Red FulcrumS-3",0)
trigger.action.setUserFlag("Vody Red FlankerD-1",0)
trigger.action.setUserFlag("Vody Red FlankerD-2",0)
trigger.action.setUserFlag("Vody Red FlankerD-3",0)
trigger.action.setUserFlag("Vody Red FlankerL-1",0)
trigger.action.setUserFlag("Vody Red FlankerL-2",0)
trigger.action.setUserFlag("Vody Red FlankerL-3",0)
trigger.action.setUserFlag("Vody Red Farmer-1",0)
trigger.action.setUserFlag("Vody Red Farmer-2",0)
trigger.action.setUserFlag("Vody Red Farmer-3",0)
trigger.action.setUserFlag("Vody Red F16-1",0)
trigger.action.setUserFlag("Vody Red F16-2",0)
trigger.action.setUserFlag("Vody Red F16-3",0)
trigger.action.setUserFlag("Vody Red F14A-1",0)
trigger.action.setUserFlag("Vody Red F14A-2",0)
trigger.action.setUserFlag("Vody Red F14A-3",0)
trigger.action.setUserFlag("Vody Red F5E-1",0)
trigger.action.setUserFlag("Vody Red F5E-2",0)
trigger.action.setUserFlag("Vody Red F5E-3",0)
