local huey1=RAT:New("RAT_Huey")
huey1:SetDeparture("CYPRUSRAT")
huey1:SetTakeoff("cold")
huey1:SetMaxDistance(100)
huey1:ContinueJourney()
huey1:Spawn(2)

local yak40=RAT:New("YAK40")
yak40:SetDeparture("CYPRUSRAT")
yak40:SetTakeoff("cold")
yak40:SetMaxDistance(100)
yak40:ContinueJourney()
yak40:Spawn(2)

local yak52=RAT:New("YAK52")
yak52:SetDeparture("CYPRUSRAT")
yak52:SetTakeoff("cold")
yak52:SetMaxDistance(100)
yak52:ContinueJourney()
yak52:Spawn(2)

local aeroflot=RAT:New("Aeroflot")
aeroflot:SetDeparture("CYPRUSRAT")
aeroflot:SetTakeoff("cold")
aeroflot:SetMaxDistance(100)
aeroflot:ContinueJourney()
aeroflot:Spawn(1)

local gazprom=RAT:New("Gazprom")
gazprom:SetDeparture("CYPRUSRAT")
gazprom:SetTakeoff("cold")
gazprom:SetMaxDistance(100)
gazprom:ContinueJourney()
gazprom:Spawn(1)

local Kazanvz=RAT:New("KazanVZ")
Kazanvz:SetDeparture("CYPRUSRAT")
Kazanvz:SetTakeoff("cold")
Kazanvz:SetMaxDistance(100)
Kazanvz:ContinueJourney()
Kazanvz:Spawn(1)

local liigromov=RAT:New("LiiGromov")
liigromov:SetDeparture("CYPRUSRAT")
liigromov:SetTakeoff("cold")
liigromov:SetMaxDistance(100)
liigromov:ContinueJourney()
liigromov:Spawn(1)

local naryanmar=RAT:New("NaryanMar")
naryanmar:SetDeparture("CYPRUSRAT")
naryanmar:SetTakeoff("cold")
naryanmar:SetMaxDistance(100)
naryanmar:ContinueJourney()
naryanmar:Spawn(1)

local projectcurium=RAT:New("ProjectCurium")
projectcurium:SetDeparture("CYPRUSRAT")
projectcurium:SetTakeoff("cold")
projectcurium:SetMaxDistance(100)
projectcurium:ContinueJourney()
projectcurium:Spawn(1)

local ka26=RAT:New("KA26")
ka26:SetDeparture("CYPRUSRAT")
ka26:SetTakeoff("cold")
ka26:SetMaxDistance(100)
ka26:ContinueJourney()
ka26:Spawn(2)

local mi26=RAT:New("MI26")
mi26:SetDeparture("CYPRUSRAT")
mi26:SetTakeoff("cold")
mi26:SetMaxDistance(100)
mi26:ContinueJourney()
mi26:Spawn(2)

local ruamb=RAT:New("RUAMB")
ruamb:SetDeparture("CYPRUSRAT")
ruamb:SetTakeoff("cold")
ruamb:SetMaxDistance(100)
ruamb:ContinueJourney()
ruamb:Spawn(1)

local ruspolice=RAT:New("RusPolice")
ruspolice:SetDeparture("CYPRUSRAT")
ruspolice:SetTakeoff("cold")
ruspolice:SetMaxDistance(100)
ruspolice:ContinueJourney()
ruspolice:Spawn(1)

local utair=RAT:New("UTair")
utair:SetDeparture("CYPRUSRAT")
utair:SetTakeoff("cold")
utair:SetMaxDistance(100)
utair:ContinueJourney()
utair:Spawn(1)

local vertolety22880=RAT:New("Vertolety22880")
vertolety22880:SetDeparture("CYPRUSRAT")
vertolety22880:SetTakeoff("cold")
vertolety22880:SetMaxDistance(100)
vertolety22880:ContinueJourney()
vertolety22880:Spawn(1)

local vertolety=RAT:New("Vertolety")
vertolety:SetDeparture("CYPRUSRAT")
vertolety:SetTakeoff("cold")
vertolety:SetMaxDistance(100)
vertolety:ContinueJourney()
vertolety:Spawn(1)

local an26=RAT:New("AeroflotAN26")
an26:SetDeparture("CYPRUSRAT")
an26:SetTakeoff("cold")
an26:SetMaxDistance(100)
an26:ContinueJourney()
an26:Spawn(1)

local il76=RAT:New("Aeroflotil76")
il76:SetDeparture("CYPRUSRAT")
il76:SetTakeoff("cold")
il76:SetMaxDistance(100)
il76:ContinueJourney()
il76:Spawn(1)

local cc130=RAT:New("CC130")
cc130:SetDeparture("CYPRUSRAT")
cc130:SetTakeoff("cold")
cc130:SetMaxDistance(100)
cc130:ContinueJourney()
cc130:Spawn(1)

local cc17=RAT:New("CC17")
cc17:SetDeparture("CYPRUSRAT")
cc17:SetTakeoff("cold")
cc17:SetMaxDistance(100)
cc17:ContinueJourney()
cc17:Spawn(1)
