trigger.action.setUserFlag("SSB",100)

--Red KM76
trigger.action.setUserFlag("KM76 Hind-1",0)
trigger.action.setUserFlag("KM76 Hind-2",0)
trigger.action.setUserFlag("KM76 Hind-3",0)
trigger.action.setUserFlag("KM76 Hind-4",0)
trigger.action.setUserFlag("KM76 Shark-1",0)
trigger.action.setUserFlag("KM76 Shark-2",0)
trigger.action.setUserFlag("KM76 Shark-3",0)
trigger.action.setUserFlag("KM76 Shark-4",0)
trigger.action.setUserFlag("KM76 Hip-1",0)
trigger.action.setUserFlag("KM76 Hip-2",0)
trigger.action.setUserFlag("KM76 Hip-3",0)
trigger.action.setUserFlag("KM76 Hip-4",0)
--captured KM76
trigger.action.setUserFlag("KM76 Hind-1",100)
trigger.action.setUserFlag("KM76 Hind-2",100)
trigger.action.setUserFlag("KM76 Hind-3",100)
trigger.action.setUserFlag("KM76 Hind-4",100)
trigger.action.setUserFlag("KM76 Shark-1",100)
trigger.action.setUserFlag("KM76 Shark-2",100)
trigger.action.setUserFlag("KM76 Shark-3",100)
trigger.action.setUserFlag("KM76 Shark-4",100)
trigger.action.setUserFlag("KM76 Hip-1",100)
trigger.action.setUserFlag("KM76 Hip-2",100)
trigger.action.setUserFlag("KM76 Hip-3",100)
trigger.action.setUserFlag("KM76 Hip-4",100)




--Red KM88
trigger.action.setUserFlag("KM88 Hind-1",0)
trigger.action.setUserFlag("KM88 Hind-2",0)
trigger.action.setUserFlag("KM88 Hind-3",0)
trigger.action.setUserFlag("KM88 Hind-4",0)
trigger.action.setUserFlag("KM88 Hip-1",0)
trigger.action.setUserFlag("KM88 Hip-2",0)
trigger.action.setUserFlag("KM88 Hip-3",0)
trigger.action.setUserFlag("KM88 Hip-4",0)
--Captured KM88
trigger.action.setUserFlag("KM88 Hind-1",100)
trigger.action.setUserFlag("KM88 Hind-2",100)
trigger.action.setUserFlag("KM88 Hind-3",100)
trigger.action.setUserFlag("KM88 Hind-4",100)
trigger.action.setUserFlag("KM88 Hip-1",100)
trigger.action.setUserFlag("KM88 Hip-2",100)
trigger.action.setUserFlag("KM88 Hip-3",100)
trigger.action.setUserFlag("KM88 Hip-4",100)



--blue LM08
trigger.action.setUserFlag("LM08 Gazelle-1",0)
trigger.action.setUserFlag("LM08 Gazelle-2",0)
trigger.action.setUserFlag("LM08 Gazelle-3",0)
trigger.action.setUserFlag("LM08 Gazelle-4",0)
trigger.action.setUserFlag("LM08 Huey-1",0)
trigger.action.setUserFlag("LM08 Huey-2",0)
trigger.action.setUserFlag("LM08 Huey-3",0)
trigger.action.setUserFlag("LM08 Huey-4",0)
--Captured LM08
trigger.action.setUserFlag("LM08 Gazelle-1",100)
trigger.action.setUserFlag("LM08 Gazelle-2",100)
trigger.action.setUserFlag("LM08 Gazelle-3",100)
trigger.action.setUserFlag("LM08 Gazelle-4",100)
trigger.action.setUserFlag("LM08 Huey-1",100)
trigger.action.setUserFlag("LM08 Huey-2",100)
trigger.action.setUserFlag("LM08 Huey-3",100)
trigger.action.setUserFlag("LM08 Huey-4",100)

--Red LM26
trigger.action.setUserFlag("LM26 Shark-1",0)
trigger.action.setUserFlag("LM26 Shark-2",0)
trigger.action.setUserFlag("LM26 Shark-3",0)
trigger.action.setUserFlag("LM26 Shark-4",0)
trigger.action.setUserFlag("LM26 Hip-1",0)
trigger.action.setUserFlag("LM26 Hip-2",0)
trigger.action.setUserFlag("LM26 Hip-3",0)
trigger.action.setUserFlag("LM26 Hip-4",0)
--captured LM26
trigger.action.setUserFlag("LM26 Shark-1",100)
trigger.action.setUserFlag("LM26 Shark-2",100)
trigger.action.setUserFlag("LM26 Shark-3",100)
trigger.action.setUserFlag("LM26 Shark-4",100)
trigger.action.setUserFlag("LM26 Hip-1",100)
trigger.action.setUserFlag("LM26 Hip-2",100)
trigger.action.setUserFlag("LM26 Hip-3",100)
trigger.action.setUserFlag("LM26 Hip-4",100)

--Blue LM26
trigger.action.setUserFlag("LM26 Apache-1",0)
trigger.action.setUserFlag("LM26 Apache-2",0)
trigger.action.setUserFlag("LM26 Apache-3",0)
trigger.action.setUserFlag("LM26 Apache-4",0)
trigger.action.setUserFlag("LM26 Huey-1",0)
trigger.action.setUserFlag("LM26 Huey-2",0)
trigger.action.setUserFlag("LM26 Huey-3",0)
trigger.action.setUserFlag("LM26 Huey-4",0)
--captured KM76
trigger.action.setUserFlag("LM26 Apache-1",100)
trigger.action.setUserFlag("LM26 Apache-2",100)
trigger.action.setUserFlag("LM26 Apache-3",100)
trigger.action.setUserFlag("LM26 Apache-4",100)
trigger.action.setUserFlag("LM26 Huey-1",100)
trigger.action.setUserFlag("LM26 Huey-2",100)
trigger.action.setUserFlag("LM26 Huey-3",100)
trigger.action.setUserFlag("LM26 Huey-4",100)

--blue Gudauta
trigger.action.setUserFlag("Gudauta Blue Viper-1",0)


--red Gudauta
trigger.action.setUserFlag("Gudauta Blue Viper-1",100)


--Blue Senaki
trigger.action.setUserFlag("Senaki Veteran Mirage-1",0)
trigger.action.setUserFlag("Senaki Veteran Mirage-2",0)
trigger.action.setUserFlag("Senaki Veteran Mirage-3",0)
trigger.action.setUserFlag("Senaki Veteran Viggen-1",0)
trigger.action.setUserFlag("Senaki Veteran Viggen-2",0)
trigger.action.setUserFlag("Senaki Veteran Viggen-3",0)
trigger.action.setUserFlag("Senaki Ace Harry-1",0)
trigger.action.setUserFlag("Senaki Ace Harry-2",0)
trigger.action.setUserFlag("Senaki Ace Harry-3",0)
trigger.action.setUserFlag("Senaki Ace Hog-1",0)
trigger.action.setUserFlag("Senaki Ace Hog-2",0)
trigger.action.setUserFlag("Senaki Ace Hog-3",0)
trigger.action.setUserFlag("Senaki Ace Tomcat-1",0)
trigger.action.setUserFlag("Senaki Ace Tomcat-2",0)
trigger.action.setUserFlag("Senaki Ace Tomcat-3",0)
trigger.action.setUserFlag("Senaki Ace Viper-1",0)
trigger.action.setUserFlag("Senaki Ace Viper-2",0)
trigger.action.setUserFlag("Senaki Ace Viper-3",0)
trigger.action.setUserFlag("Senaki Rookie Tiger-1",0)
trigger.action.setUserFlag("Senaki Rookie Tiger-2",0)
trigger.action.setUserFlag("Senaki Rookie Tiger-3",0)
trigger.action.setUserFlag("Senaki Ace Eagle-1",0)
trigger.action.setUserFlag("Senaki Ace Eagle-2",0)
trigger.action.setUserFlag("Senaki Ace Eagle-3",0)
trigger.action.setUserFlag("Senaki Ace Hornet-1",0)
trigger.action.setUserFlag("Senaki Ace Hornet-2",0)
trigger.action.setUserFlag("Senaki Ace Hornet-3",0)
trigger.action.setUserFlag("Senaki Ace Frogfoot-1",100)
trigger.action.setUserFlag("Senaki Ace Frogfoot-2",100)
trigger.action.setUserFlag("Senaki Ace Frogfoot-3",100)
trigger.action.setUserFlag("Senaki Rookie Fishbed-1",100)
trigger.action.setUserFlag("Senaki Rookie Fishbed-2",100)
trigger.action.setUserFlag("Senaki Rookie Fishbed-3",100)
trigger.action.setUserFlag("Senaki Ace Fulcrum-1",100)
trigger.action.setUserFlag("Senaki Ace Fulcrum-2",100)
trigger.action.setUserFlag("Senaki Ace Fulcrum-3",100)
trigger.action.setUserFlag("Senaki Ace FlankerD-1",100)
trigger.action.setUserFlag("Senaki Ace FlankerD-2",100)
trigger.action.setUserFlag("Senaki Ace FlankerD-3",100)
trigger.action.setUserFlag("Senaki Ace Flanker-1",100)
trigger.action.setUserFlag("Senaki Ace Flanker-2",100)
trigger.action.setUserFlag("Senaki Ace Flanker-3",100)
trigger.action.setUserFlag("Senaki Rookie Farmer-1",100)
trigger.action.setUserFlag("Senaki Rookie Farmer-1",100)
trigger.action.setUserFlag("Senaki Rookie Farmer-1",100)
trigger.action.setUserFlag("Senaki Rookie Frogfoot-1",100)
trigger.action.setUserFlag("Senaki Rookie Frogfoot-2",100)
trigger.action.setUserFlag("Senaki Rookie Frogfoot-3",100)
trigger.action.setUserFlag("Senaki Ace Thunder-1",100)
trigger.action.setUserFlag("Senaki Ace Thunder-2",100)
trigger.action.setUserFlag("Senaki Ace Thunder-3",100)


--red Senaki
trigger.action.setUserFlag("Senaki Veteran Mirage-1",100)
trigger.action.setUserFlag("Senaki Veteran Mirage-2",100)
trigger.action.setUserFlag("Senaki Veteran Mirage-3",100)
trigger.action.setUserFlag("Senaki Veteran Viggen-1",100)
trigger.action.setUserFlag("Senaki Veteran Viggen-2",100)
trigger.action.setUserFlag("Senaki Veteran Viggen-3",100)
trigger.action.setUserFlag("Senaki Ace Harry-1",100)
trigger.action.setUserFlag("Senaki Ace Harry-2",100)
trigger.action.setUserFlag("Senaki Ace Harry-3",100)
trigger.action.setUserFlag("Senaki Ace Hog-1",100)
trigger.action.setUserFlag("Senaki Ace Hog-2",100)
trigger.action.setUserFlag("Senaki Ace Hog-3",100)
trigger.action.setUserFlag("Senaki Ace Tomcat-1",100)
trigger.action.setUserFlag("Senaki Ace Tomcat-2",100)
trigger.action.setUserFlag("Senaki Ace Tomcat-3",100)
trigger.action.setUserFlag("Senaki Ace Viper-1",100)
trigger.action.setUserFlag("Senaki Ace Viper-2",100)
trigger.action.setUserFlag("Senaki Ace Viper-3",100)
trigger.action.setUserFlag("Senaki Rookie Tiger-1",100)
trigger.action.setUserFlag("Senaki Rookie Tiger-2",100)
trigger.action.setUserFlag("Senaki Rookie Tiger-3",100)
trigger.action.setUserFlag("Senaki Ace Eagle-1",100)
trigger.action.setUserFlag("Senaki Ace Eagle-2",100)
trigger.action.setUserFlag("Senaki Ace Eagle-3",100)
trigger.action.setUserFlag("Senaki Ace Hornet-1",100)
trigger.action.setUserFlag("Senaki Ace Hornet-2",100)
trigger.action.setUserFlag("Senaki Ace Hornet-3",100)
trigger.action.setUserFlag("Senaki Ace Frogfoot-1",0)
trigger.action.setUserFlag("Senaki Ace Frogfoot-2",0)
trigger.action.setUserFlag("Senaki Ace Frogfoot-3",0)
trigger.action.setUserFlag("Senaki Rookie Fishbed-1",0)
trigger.action.setUserFlag("Senaki Rookie Fishbed-2",0)
trigger.action.setUserFlag("Senaki Rookie Fishbed-3",0)
trigger.action.setUserFlag("Senaki Ace Fulcrum-1",0)
trigger.action.setUserFlag("Senaki Ace Fulcrum-2",0)
trigger.action.setUserFlag("Senaki Ace Fulcrum-3",0)
trigger.action.setUserFlag("Senaki Ace FlankerD-1",0)
trigger.action.setUserFlag("Senaki Ace FlankerD-2",0)
trigger.action.setUserFlag("Senaki Ace FlankerD-3",0)
trigger.action.setUserFlag("Senaki Ace Flanker-1",0)
trigger.action.setUserFlag("Senaki Ace Flanker-2",0)
trigger.action.setUserFlag("Senaki Ace Flanker-3",0)
trigger.action.setUserFlag("Senaki Rookie Farmer-1",0)
trigger.action.setUserFlag("Senaki Rookie Farmer-1",0)
trigger.action.setUserFlag("Senaki Rookie Farmer-1",0)
trigger.action.setUserFlag("Senaki Rookie Frogfoot-1",0)
trigger.action.setUserFlag("Senaki Rookie Frogfoot-2",0)
trigger.action.setUserFlag("Senaki Rookie Frogfoot-3",0)
trigger.action.setUserFlag("Senaki Ace Thunder-1",0)
trigger.action.setUserFlag("Senaki Ace Thunder-2",0)
trigger.action.setUserFlag("Senaki Ace Thunder-3",0)

--blue Vody
trigger.action.setUserFlag("Vody Blue Viper-1",0)
trigger.action.setUserFlag("Vody Blue Viper-2",0)
trigger.action.setUserFlag("Vody Blue Viper-3",0)
trigger.action.setUserFlag("Vody Blue Mirage-1",0)
trigger.action.setUserFlag("Vody Blue Mirage-2",0)
trigger.action.setUserFlag("Vody Blue Mirage-3",0)
trigger.action.setUserFlag("Vody Blue WarthogC2-1",0)
trigger.action.setUserFlag("Vody Blue WarthogC2-2",0)
trigger.action.setUserFlag("Vody Blue WarthogC2-3",0)
trigger.action.setUserFlag("Vody Blue WarthogA-1",0)
trigger.action.setUserFlag("Vody Blue WarthogA-2",0)
trigger.action.setUserFlag("Vody Blue Viggen-1",0)
trigger.action.setUserFlag("Vody Blue Viggen-2",0)
trigger.action.setUserFlag("Vody Blue Harrier-1",0)
trigger.action.setUserFlag("Vody Blue Harrier-2",0)
trigger.action.setUserFlag("Vody Blue Hornet-1",0)
trigger.action.setUserFlag("Vody Blue Hornet-2",0)
trigger.action.setUserFlag("Vody Blue Hornet-3",0)
trigger.action.setUserFlag("Vody Blue TomcatB-1",0)
trigger.action.setUserFlag("Vody Blue TomcatB-2",0)
trigger.action.setUserFlag("Vody Blue TomcatB-3",0)
trigger.action.setUserFlag("Vody Blue Tiger-1",0)
trigger.action.setUserFlag("Vody Blue Tiger-2",0)
trigger.action.setUserFlag("Vody Blue Tiger-3",0)
trigger.action.setUserFlag("Vody Blue Eagle-1",0)
trigger.action.setUserFlag("Vody Blue Eagle-2",0)
trigger.action.setUserFlag("Vody Blue Eagle-3",0)
trigger.action.setUserFlag("Vody Red SU25-1",100)
trigger.action.setUserFlag("Vody Red SU25-2",100)
trigger.action.setUserFlag("Vody Red SU25-3",100)
trigger.action.setUserFlag("Vody Red SU25T-1",100)
trigger.action.setUserFlag("Vody Red SU25T-2",100)
trigger.action.setUserFlag("Vody Red SU25T-3",100)
trigger.action.setUserFlag("Vody Red Thunder-1",100)
trigger.action.setUserFlag("Vody Red Thunder-2",100)
trigger.action.setUserFlag("Vody Red Thunder-3",100)
trigger.action.setUserFlag("Vody Red Fishbed-1",100)
trigger.action.setUserFlag("Vody Red Fishbed-2",100)
trigger.action.setUserFlag("Vody Red Fishbed-3",100)
trigger.action.setUserFlag("Vody Red FulcrumA-1",100)
trigger.action.setUserFlag("Vody Red FulcrumA-2",100)
trigger.action.setUserFlag("Vody Red FulcrumA-3",100)
trigger.action.setUserFlag("Vody Red FulcrumS-1",100)
trigger.action.setUserFlag("Vody Red FulcrumS-2",100)
trigger.action.setUserFlag("Vody Red FulcrumS-3",100)
trigger.action.setUserFlag("Vody Red FlankerD-1",100)
trigger.action.setUserFlag("Vody Red FlankerD-2",100)
trigger.action.setUserFlag("Vody Red FlankerD-3",100)
trigger.action.setUserFlag("Vody Red FlankerL-1",100)
trigger.action.setUserFlag("Vody Red FlankerL-2",100)
trigger.action.setUserFlag("Vody Red FlankerL-3",100)
trigger.action.setUserFlag("Vody Red Farmer-1",100)
trigger.action.setUserFlag("Vody Red Farmer-2",100)
trigger.action.setUserFlag("Vody Red Farmer-3",100)
trigger.action.setUserFlag("Vody Red F16-1",100)
trigger.action.setUserFlag("Vody Red F16-2",100)
trigger.action.setUserFlag("Vody Red F16-3",100)
trigger.action.setUserFlag("Vody Red F14A-1",100)
trigger.action.setUserFlag("Vody Red F14A-2",100)
trigger.action.setUserFlag("Vody Red F14A-3",100)
trigger.action.setUserFlag("Vody Red F5E-1",100)
trigger.action.setUserFlag("Vody Red F5E-2",100)
trigger.action.setUserFlag("Vody Red F5E-3",100)

--red Vody
trigger.action.setUserFlag("Vody Blue Viper-1",100)
trigger.action.setUserFlag("Vody Blue Viper-2",100)
trigger.action.setUserFlag("Vody Blue Viper-3",100)
trigger.action.setUserFlag("Vody Blue Mirage-1",100)
trigger.action.setUserFlag("Vody Blue Mirage-2",100)
trigger.action.setUserFlag("Vody Blue Mirage-3",100)
trigger.action.setUserFlag("Vody Blue WarthogC2-1",100)
trigger.action.setUserFlag("Vody Blue WarthogC2-2",100)
trigger.action.setUserFlag("Vody Blue WarthogC2-3",100)
trigger.action.setUserFlag("Vody Blue WarthogA-1",100)
trigger.action.setUserFlag("Vody Blue WarthogA-2",100)
trigger.action.setUserFlag("Vody Blue Viggen-1",100)
trigger.action.setUserFlag("Vody Blue Viggen-2",100)
trigger.action.setUserFlag("Vody Blue Harrier-1",100)
trigger.action.setUserFlag("Vody Blue Harrier-2",100)
trigger.action.setUserFlag("Vody Blue Hornet-1",100)
trigger.action.setUserFlag("Vody Blue Hornet-2",100)
trigger.action.setUserFlag("Vody Blue Hornet-3",100)
trigger.action.setUserFlag("Vody Blue TomcatB-1",100)
trigger.action.setUserFlag("Vody Blue TomcatB-2",100)
trigger.action.setUserFlag("Vody Blue TomcatB-3",100)
trigger.action.setUserFlag("Vody Blue Tiger-1",100)
trigger.action.setUserFlag("Vody Blue Tiger-2",100)
trigger.action.setUserFlag("Vody Blue Tiger-3",100)
trigger.action.setUserFlag("Vody Blue Eagle-1",100)
trigger.action.setUserFlag("Vody Blue Eagle-2",100)
trigger.action.setUserFlag("Vody Blue Eagle-3",100)
trigger.action.setUserFlag("Vody Red SU25-1",0)
trigger.action.setUserFlag("Vody Red SU25-2",0)
trigger.action.setUserFlag("Vody Red SU25-3",0)
trigger.action.setUserFlag("Vody Red SU25T-1",0)
trigger.action.setUserFlag("Vody Red SU25T-2",0)
trigger.action.setUserFlag("Vody Red SU25T-3",0)
trigger.action.setUserFlag("Vody Red Thunder-1",0)
trigger.action.setUserFlag("Vody Red Thunder-2",0)
trigger.action.setUserFlag("Vody Red Thunder-3",0)
trigger.action.setUserFlag("Vody Red Fishbed-1",0)
trigger.action.setUserFlag("Vody Red Fishbed-2",0)
trigger.action.setUserFlag("Vody Red Fishbed-3",0)
trigger.action.setUserFlag("Vody Red FulcrumA-1",0)
trigger.action.setUserFlag("Vody Red FulcrumA-2",0)
trigger.action.setUserFlag("Vody Red FulcrumA-3",0)
trigger.action.setUserFlag("Vody Red FulcrumS-1",0)
trigger.action.setUserFlag("Vody Red FulcrumS-2",0)
trigger.action.setUserFlag("Vody Red FulcrumS-3",0)
trigger.action.setUserFlag("Vody Red FlankerD-1",0)
trigger.action.setUserFlag("Vody Red FlankerD-2",0)
trigger.action.setUserFlag("Vody Red FlankerD-3",0)
trigger.action.setUserFlag("Vody Red FlankerL-1",0)
trigger.action.setUserFlag("Vody Red FlankerL-2",0)
trigger.action.setUserFlag("Vody Red FlankerL-3",0)
trigger.action.setUserFlag("Vody Red Farmer-1",0)
trigger.action.setUserFlag("Vody Red Farmer-2",0)
trigger.action.setUserFlag("Vody Red Farmer-3",0)
trigger.action.setUserFlag("Vody Red F16-1",0)
trigger.action.setUserFlag("Vody Red F16-2",0)
trigger.action.setUserFlag("Vody Red F16-3",0)
trigger.action.setUserFlag("Vody Red F14A-1",0)
trigger.action.setUserFlag("Vody Red F14A-2",0)
trigger.action.setUserFlag("Vody Red F14A-3",0)
trigger.action.setUserFlag("Vody Red F5E-1",0)
trigger.action.setUserFlag("Vody Red F5E-2",0)
trigger.action.setUserFlag("Vody Red F5E-3",0)
