blufor = SET_GROUP:New():FilterCoalitions('blue'):FilterCategoryGround():FilterStart()
redfor = SET_GROUP:New():FilterCoalitions('red'):FilterCategoryGround():FilterStart()
MasterZone = ZONE:FindByName("MonkeyFucker")
env.info("----------------------------KM76 RedFor Spawns--------------------------")
function KM76ClientSpawn()
  env.info("KM76ClientSpawn FUNCTION STARTED")
     local KM76zone = ZONE:FindByName("KM76")
     KM76Hind1 = GROUP:New("KM76 Hind-1")
     KM76Hind2 = GROUP:New("KM76 Hind-2")
     KM76Hind3 = GROUP:New("KM76 Hind-3")
     KM76Hind4 = GROUP:New("KM76 Hind-4")
     KM76Shark1 = GROUP:New("KM76 Shark-1")
     KM76Shark2 = GROUP:New("KM76 Shark-2")
     KM76Shark3 = GROUP:New("KM76 Shark-3")
     KM76Shark4 = GROUP:New("KM76 Shark-4")
     KM76Hip1 = GROUP:New("KM76 Hip-1")
     KM76Hip2 = GROUP:New("KM76 Hip-2")
     KM76Hip3 = GROUP:New("KM76 Hip-3")
     KM76Hip4 = GROUP:New("KM76 Hip-4")

     if blufor:NoneInZone(KM76zone) then
       trigger.action.activateGroup(KM76Hind1)
       trigger.action.activateGroup(KM76Hind2)
       trigger.action.activateGroup(KM76Hind3)
       trigger.action.activateGroup(KM76Hind4)
       trigger.action.activateGroup(KM76Shark1)
       trigger.action.activateGroup(KM76Shark2)
       trigger.action.activateGroup(KM76Shark3)
       trigger.action.activateGroup(KM76Shark4)
       trigger.action.activateGroup(KM76Hip1)
       trigger.action.activateGroup(KM76Hip2)
       trigger.action.activateGroup(KM76Hip3)
       trigger.action.activateGroup(KM76Hip4)
     end
   end
     timer.scheduleFunction(KM76ClientSpawn, {}, timer.getTime{}+2)
     env.info("----------------------------KM76ClientSpawn TIMER STARTED--------------------------")
