-- LeHarvePort:AddShippingLane(warehouseLeHavrePort, LeHarvePort2GrandCampLesBainsPortUnit, false)

---------------------REQESTORS---------------------
--warehouseCherbourg:AddRequest(warehouseLittleHampton, WAREHOUSE.Descriptor.ATTRIBUTE, WAREHOUSE.Attribute.GROUND_INFANTRY, 5, WAREHOUSE.TransportType.NAVAL_ARMEDSHIP, 2)
-- warehouseCherbourg:SetMarker(true)

-- Groups for the warehouses  ----------RED----------
infantryRed = GROUP:FindByName("InfantryK98")
Tiger2Red = GROUP:FindByName("Tiger2")
JagpantherTDRed = GROUP:FindByName("JagpantherTD")
ScoutPumaRed = GROUP:FindByName("ScoutPuma")
APCHalfTrackRed = GROUP:FindByName("APCHalfTrack")
SPHWespe105Red = GROUP:FindByName("SPHWespe105")
KubelwagenJeepRed = GROUP:FindByName("KubelwagenJeep")
OpelBlitzTruckRed = GROUP:FindByName("OpelBlitzTruck")
HorchStaffCarRed = GROUP:FindByName("HorchStaffCar")
BF109K4Red = GROUP:FindByName("BF109K4")
FW190A8Red = GROUP:FindByName("FW190A8")
FW190D9Red = GROUP:FindByName("FW190D9")
JU88A4Red = GROUP:FindByName("JU88A4")
SchnellbootS130Red = GROUP:FindByName("SchnellbootS130")

----------- RED WAREHOUSE INVENTORY ---------------------------
warehouseEvreux:AddAsset(infantryRed, 5000)
warehouseEvreux:AddAsset(Tiger2Red, 500)
warehouseEvreux:AddAsset(JagpantherTDRed, 500)
warehouseEvreux:AddAsset(ScoutPumaRed, 500)
warehouseEvreux:AddAsset(APCHalfTrackRed, 500)
warehouseEvreux:AddAsset(SPHWespe105Red, 500)
warehouseEvreux:AddAsset(KubelwagenJeepRed, 500)
warehouseEvreux:AddAsset(OpelBlitzTruckRed, 500)
warehouseEvreux:AddAsset(HorchStaffCarRed, 500)
warehouseEvreux:AddAsset(BF109K4Red, 500)
warehouseEvreux:AddAsset(FW190A8Red, 500)
warehouseEvreux:AddAsset(FW190D9Red, 500)
warehouseEvreux:AddAsset(JU88A4Red, 500)
--*******CARPIQUET********--
warehouseCarpiquet:AddAsset(infantryRed, 5000)
warehouseCarpiquet:AddAsset(Tiger2Red, 500)
warehouseCarpiquet:AddAsset(JagpantherTDRed, 500)
warehouseCarpiquet:AddAsset(ScoutPumaRed, 500)
warehouseCarpiquet:AddAsset(APCHalfTrackRed, 500)
warehouseCarpiquet:AddAsset(SPHWespe105Red, 500)
warehouseCarpiquet:AddAsset(KubelwagenJeepRed, 500)
warehouseCarpiquet:AddAsset(OpelBlitzTruckRed, 500)
warehouseCarpiquet:AddAsset(HorchStaffCarRed, 500)
warehouseCarpiquet:AddAsset(BF109K4Red, 500)
warehouseCarpiquet:AddAsset(FW190A8Red, 500)
warehouseCarpiquet:AddAsset(FW190D9Red, 500)
warehouseCarpiquet:AddAsset(JU88A4Red, 500)

--*******LEHARVEPORT********--
-- warehouseLeHavrePort:AddAsset(infantryRed, 5)
-- warehouseLeHavrePort:AddAsset(Tiger2Red, 5)
-- warehouseLeHavrePort:AddAsset(JagpantherTDRed, 5)
-- warehouseLeHavrePort:AddAsset(ScoutPumaRed, 5)
-- warehouseLeHavrePort:AddAsset(APCHalfTrackRed, 5)
-- warehouseLeHavrePort:AddAsset(SPHWespe105Red, 5)
-- warehouseLeHavrePort:AddAsset(KubelwagenJeepRed, 5)
-- warehouseLeHavrePort:AddAsset(OpelBlitzTruckRed, 5)
-- warehouseLeHavrePort:AddAsset(HorchStaffCarRed, 5)
-- warehouseLeHavrePort:AddAsset(BF109K4Red, 5)
-- warehouseLeHavrePort:AddAsset(FW190A8Red, 5)
-- warehouseLeHavrePort:AddAsset(FW190D9Red, 5)
-- warehouseLeHavrePort:AddAsset(JU88A4Red, 5)
warehouseLeHavrePort:AddAsset(SchnellbootS130Red, 50, WAREHOUSE.Attribute.NAVAL_ARMEDSHIP)
