-- LeHarvePort:AddShippingLane(warehouseLeHavrePort, LeHarvePort2GrandCampLesBainsPortUnit, false)

---------------------REQESTORS---------------------
--warehouseCherbourg:AddRequest(warehouseLittleHampton, WAREHOUSE.Descriptor.ATTRIBUTE, WAREHOUSE.Attribute.GROUND_INFANTRY, 5, WAREHOUSE.TransportType.NAVAL_ARMEDSHIP, 2)
-- warehouseCherbourg:SetMarker(true)

-- Groups for the warehouses  --------------------
GERInfantry = GROUP:FindByName("GER Infantry K98")
GERTiger2 = GROUP:FindByName("GER Tiger 2")
GERJagpantherTD = GROUP:FindByName("GER Jagpanther TD")
GERScoutPuma = GROUP:FindByName("GER Scout Puma")
GERAPCHalfTrack = GROUP:FindByName("GER APC Half Track")
GERSPHWespe105 = GROUP:FindByName("GER SPH Wespe 105")
GERKubelwagenJeep = GROUP:FindByName("GER Kubelwagen Jeep")
GEROpelBlitzTruck = GROUP:FindByName("GER Opel Blitz Truck")
GERHorchStaffCar = GROUP:FindByName("GER Horch Staff Car")
GERBF109K4 = GROUP:FindByName("GER BF109 K4")
GERFW190A8 = GROUP:FindByName("GER FW190 A8")
GERFW190D9 = GROUP:FindByName("GER FW190 D9")
GERJU88A4 = GROUP:FindByName("GER JU88 A4")
GERSchnellbootS130 = GROUP:FindByName("GER Schnellboot S130")

-----------  WAREHOUSE INVENTORY ---------------------------
-- warehouseEvreux:AddAsset(GERInfantry, 5000)
-- warehouseEvreux:AddAsset(GERTiger2, 500)
-- warehouseEvreux:AddAsset(GERJagpantherTD, 500)
-- warehouseEvreux:AddAsset(GERScoutPuma, 500)
-- warehouseEvreux:AddAsset(GERAPCHalfTrack, 500)
-- warehouseEvreux:AddAsset(GERSPHWespe105, 500)
-- warehouseEvreux:AddAsset(GERKubelwagenJeep, 500)
-- warehouseEvreux:AddAsset(GEROpelBlitzTruck, 500)
-- warehouseEvreux:AddAsset(GERHorchStaffCar, 500)
-- warehouseEvreux:AddAsset(GERBF109K4, 500)
-- warehouseEvreux:AddAsset(GERFW190A8, 500)
-- warehouseEvreux:AddAsset(GERFW190D9, 500)
-- warehouseEvreux:AddAsset(GERJU88A4, 500)
--*******CARPIQUET********--
warehouseCarpiquet:AddAsset(GERInfantry, 5000)
warehouseCarpiquet:AddAsset(GERTiger2, 500)
warehouseCarpiquet:AddAsset(GERJagpantherTD, 500)
warehouseCarpiquet:AddAsset(GERScoutPuma, 500)
warehouseCarpiquet:AddAsset(GERAPCHalfTrack, 500)
warehouseCarpiquet:AddAsset(GERSPHWespe105, 500)
warehouseCarpiquet:AddAsset(GERKubelwagenJeep, 500)
warehouseCarpiquet:AddAsset(GEROpelBlitzTruck, 500)
warehouseCarpiquet:AddAsset(GERHorchStaffCar, 500)
warehouseCarpiquet:AddAsset(GERBF109K4, 500)
warehouseCarpiquet:AddAsset(GERFW190A8, 500)
warehouseCarpiquet:AddAsset(GERFW190D9, 500)
warehouseCarpiquet:AddAsset(GERJU88A4, 500)

--*******LEHARVEPORT********--
-- warehouseLeHavrePort:AddAsset(infantry, 5)
-- warehouseLeHavrePort:AddAsset(Tiger2, 5)
-- warehouseLeHavrePort:AddAsset(JagpantherTD, 5)
-- warehouseLeHavrePort:AddAsset(ScoutPuma, 5)
-- warehouseLeHavrePort:AddAsset(APCHalfTrack, 5)
-- warehouseLeHavrePort:AddAsset(SPHWespe105, 5)
-- warehouseLeHavrePort:AddAsset(KubelwagenJeep, 5)
-- warehouseLeHavrePort:AddAsset(OpelBlitzTruck, 5)
-- warehouseLeHavrePort:AddAsset(HorchStaffCar, 5)
-- warehouseLeHavrePort:AddAsset(BF109K4, 5)
-- warehouseLeHavrePort:AddAsset(FW190A8, 5)
-- warehouseLeHavrePort:AddAsset(FW190D9, 5)
-- warehouseLeHavrePort:AddAsset(JU88A4, 5)
warehouseLeHavrePort:AddAsset(GERSchnellbootS130, 50, WAREHOUSE.Attribute.NAVAL_ARMEDSHIP)
